// Main Application Manager
class InterviewApp {
    constructor() {
        this.questions = [];
        this.questionSource = null; // 'llm' | 'fallback'
        this.role = 'General professional';
        this.currentQuestionIndex = 0;
        this.isInterviewActive = false;
        this.questionStartTime = null;
        this.resetSession();
        this.setupEventListeners();
        console.log('InterviewX initialized');
    }

    resetSession() {
        this.currentSession = {
            questionsAnswered: 0,
            totalPresence: 0,
            totalFillers: 0,
            aiScores: [],
            feedbackSource: null
        };
    }

    setupEventListeners() {
        document.getElementById('startInterviewBtn').addEventListener('click', () => this.startInterview());
        document.getElementById('stopInterviewBtn').addEventListener('click', () => this.stopInterview());
        document.getElementById('micBtn').addEventListener('click', () => this.toggleMicrophone());
    }

    // ------------------------------------------------------------------
    // Question sourcing: LLM first, labeled built-in bank as fallback
    // ------------------------------------------------------------------
    async prepareQuestions() {
        const role = document.getElementById('roleInput').value.trim() || 'General professional';
        const difficulty = document.getElementById('difficultySelect').value;
        const count = parseInt(document.getElementById('questionCount').value, 10) || 6;
        this.role = role;

        const sourceLabel = document.getElementById('questionSourceLabel');

        try {
            const result = await aiService.generateQuestions(role, difficulty, count);
            this.questions = result.questions;
            this.questionSource = 'llm';
            sourceLabel.innerHTML = `<span class="source-badge llm">🤖 Questions generated by ${escapeHtml(result.model)} for “${escapeHtml(role)}” (${escapeHtml(difficulty)})</span>`;
            return true;
        } catch (err) {
            console.warn('LLM question generation unavailable:', err.message);
        }

        // Fallback: built-in static bank, clearly labeled
        try {
            const response = await fetch('data/questions.json');
            const data = await response.json();
            this.questions = data.questions.slice(0, count);
        } catch {
            this.questions = [
                { question: 'Tell me about yourself and your professional background.', category: 'General', tips: 'Present → Past → Future.' },
                { question: 'What are your greatest strengths?', category: 'Self-Assessment', tips: 'Provide specific examples.' },
                { question: 'Describe a challenging situation you faced and how you handled it.', category: 'Behavioral', tips: 'Use the STAR method.' }
            ];
        }
        this.questionSource = 'fallback';
        sourceLabel.innerHTML = '<span class="source-badge offline">⚠️ Built-in question bank — generic, NOT AI-generated or role-specific</span>';
        ToastManager.show('LLM unavailable — using the built-in question bank (not AI).', 'warning', 6000);
        return true;
    }

    // ------------------------------------------------------------------
    // Interview lifecycle
    // ------------------------------------------------------------------
    async startInterview() {
        const startBtn = document.getElementById('startInterviewBtn');
        startBtn.disabled = true;
        startBtn.textContent = 'Preparing questions…';

        await this.prepareQuestions();

        const cameraResult = await cameraManager.startCamera();
        startBtn.disabled = false;
        startBtn.textContent = '▶ Start Interview';
        if (!cameraResult.success) {
            ToastManager.show(cameraResult.message, 'error');
            return;
        }

        this.currentQuestionIndex = 0;
        this.resetSession();
        chartsManager.clearData();

        this.isInterviewActive = true;
        startBtn.classList.add('hidden');
        document.getElementById('stopInterviewBtn').classList.remove('hidden');
        document.getElementById('setupPanel').classList.add('collapsed');
        document.getElementById('micBtn').style.display = 'none';

        this.startPresenceTracking();

        setTimeout(() => this.askNextQuestion(), InterviewXConfig.timing.questionStartDelayMs);
    }

    stopInterview() {
        this.isInterviewActive = false;

        cameraManager.stopCamera();
        speechManager.stopListening();
        speechManager.stopSpeaking();
        this.stopPresenceTracking();
        if (this.autoSubmitTimeout) clearTimeout(this.autoSubmitTimeout);

        document.getElementById('startInterviewBtn').classList.remove('hidden');
        document.getElementById('stopInterviewBtn').classList.add('hidden');
        document.getElementById('setupPanel').classList.remove('collapsed');
        const micBtn = document.getElementById('micBtn');
        micBtn.disabled = true;
        micBtn.textContent = '🎤 Start Speaking';
        micBtn.classList.remove('recording');

        this.saveSession();
        this.showSessionSummary();
    }

    async askNextQuestion() {
        if (!this.isInterviewActive) return;
        if (this.currentQuestionIndex >= this.questions.length) {
            this.stopInterview();
            return;
        }

        const question = this.questions[this.currentQuestionIndex];

        document.getElementById('currentQuestion').textContent = question.question;
        document.getElementById('questionCategory').textContent = question.category || '';
        document.getElementById('questionProgress').textContent =
            `Question ${this.currentQuestionIndex + 1} of ${this.questions.length}`;

        const display = document.querySelector('.question-display');
        display.classList.add('new-question');
        setTimeout(() => display.classList.remove('new-question'), 600);

        try {
            await speechManager.speakQuestion(question.question);
        } catch (error) {
            console.error('Speech error:', error);
        }

        this.questionStartTime = Date.now();
        this.startQuestionTimer();

        setTimeout(() => this.startAutoListening(), 800);
    }

    startAutoListening() {
        if (!this.isInterviewActive) return;
        speechManager.startListening();
        document.getElementById('transcriptDisplay').classList.add('listening');

        this.autoSubmitTimeout = setTimeout(() => {
            if (speechManager.getTranscript().length > InterviewXConfig.interview.minAnswerLength) {
                this.submitAnswer();
            } else if (this.isInterviewActive) {
                ToastManager.show('Say your answer out loud — listening again.', 'info');
                speechManager.stopListening();
                this.startAutoListening();
            }
        }, InterviewXConfig.timing.maxAnswerTimeMs);
    }

    toggleMicrophone() {
        const micBtn = document.getElementById('micBtn');

        if (speechManager.isListening) {
            speechManager.stopListening();
            micBtn.textContent = '🎤 Start Speaking';
            micBtn.classList.remove('recording');
            this.submitAnswer();
        } else {
            speechManager.startListening();
            micBtn.textContent = '🔴 Recording…';
            micBtn.classList.add('recording');
        }
    }

    async submitAnswer() {
        if (this.autoSubmitTimeout) clearTimeout(this.autoSubmitTimeout);

        const answer = speechManager.getTranscript();

        if (!answer || answer.length < InterviewXConfig.interview.minAnswerLength) {
            ToastManager.show('Please give a longer answer.', 'warning');
            speechManager.clearTranscript();
            this.startAutoListening();
            return;
        }

        speechManager.stopListening();
        document.getElementById('transcriptDisplay').classList.remove('listening');
        this.stopQuestionTimer();

        const responseTime = this.questionStartTime ? (Date.now() - this.questionStartTime) / 1000 : 0;
        const wordCount = speechManager.getWordCount();
        const fillerCount = speechManager.countFillerWords();
        const presenceLevel = cameraManager.getPresenceLevel();

        this.updateStats(responseTime, wordCount, fillerCount);
        this.showLoading('Evaluating your answer…');

        try {
            const analysis = await aiService.analyzeAnswer(
                this.questions[this.currentQuestionIndex].question,
                answer,
                this.role,
                { responseTime, wordCount, fillerCount }
            );

            this.displayFeedback(analysis);

            this.currentSession.questionsAnswered++;
            this.currentSession.totalPresence += presenceLevel;
            this.currentSession.totalFillers += fillerCount;
            this.currentSession.aiScores.push(analysis.score);
            this.currentSession.feedbackSource = analysis.source;
        } catch (error) {
            console.error('Feedback error:', error);
            ToastManager.show('Could not evaluate the answer.', 'error');
        } finally {
            this.hideLoading();
        }

        speechManager.clearTranscript();

        setTimeout(() => {
            this.currentQuestionIndex++;
            this.askNextQuestion();
        }, InterviewXConfig.timing.nextQuestionDelayMs);
    }

    // ------------------------------------------------------------------
    // UI helpers
    // ------------------------------------------------------------------
    updateStats(responseTime, wordCount, fillerCount) {
        document.getElementById('responseTime').textContent = Math.round(responseTime) + 's';
        document.getElementById('wordCount').textContent = wordCount;
        document.getElementById('fillerWords').textContent = fillerCount;
    }

    displayFeedback(analysis) {
        const feedbackElement = document.getElementById('aiFeedback');
        feedbackElement.innerHTML = aiService.formatFeedback(analysis);
        feedbackElement.classList.add('updating');

        const scoreEl = document.getElementById('aiScore');
        scoreEl.textContent = `${analysis.score}/10`;
        scoreEl.title = analysis.source === 'llm'
            ? `Scored by ${analysis.model}`
            : 'Offline heuristic score — not AI';

        setTimeout(() => feedbackElement.classList.remove('updating'), 500);
    }

    startQuestionTimer() {
        this.stopQuestionTimer();
        this.timerInterval = setInterval(() => {
            if (this.questionStartTime) {
                const elapsed = Math.floor((Date.now() - this.questionStartTime) / 1000);
                document.getElementById('questionTimer').textContent = `⏱ ${elapsed}s`;
            }
        }, 1000);
    }

    stopQuestionTimer() {
        if (this.timerInterval) {
            clearInterval(this.timerInterval);
            this.timerInterval = null;
        }
    }

    startPresenceTracking() {
        this.presenceInterval = setInterval(() => {
            if (this.isInterviewActive) {
                chartsManager.addDataPoint(cameraManager.getPresenceLevel());
            }
        }, InterviewXConfig.timing.chartUpdateMs);
    }

    stopPresenceTracking() {
        if (this.presenceInterval) {
            clearInterval(this.presenceInterval);
            this.presenceInterval = null;
        }
        this.stopQuestionTimer();
    }

    // ------------------------------------------------------------------
    // Session persistence & summary
    // ------------------------------------------------------------------
    sessionAverages() {
        const n = this.currentSession.questionsAnswered;
        const avgPresence = n > 0 ? Math.round(this.currentSession.totalPresence / n) : 0;
        const scores = this.currentSession.aiScores;
        const avgScore = scores.length > 0
            ? Math.round((scores.reduce((a, b) => a + b, 0) / scores.length) * 10) / 10
            : 0;
        return { avgPresence, avgScore };
    }

    saveSession() {
        const currentUser = storage.getCurrentUser();
        if (!currentUser || this.currentSession.questionsAnswered === 0) return;

        const { avgPresence, avgScore } = this.sessionAverages();

        storage.saveHistory(currentUser.username, {
            role: this.role,
            questionsAnswered: this.currentSession.questionsAnswered,
            avgPresence,
            totalFillers: this.currentSession.totalFillers,
            aiScore: avgScore,
            feedbackSource: this.currentSession.feedbackSource
        });

        authManager.loadUserHistory(currentUser.username);
    }

    showSessionSummary() {
        if (this.currentSession.questionsAnswered === 0) return;
        const { avgPresence, avgScore } = this.sessionAverages();
        const isLLM = this.currentSession.feedbackSource === 'llm';

        Modal.open({
            title: 'Interview Complete 🎉',
            bodyHtml: `
                <div class="summary-grid">
                    <div><strong>${this.currentSession.questionsAnswered}</strong><span>Questions</span></div>
                    <div><strong>${avgScore}/10</strong><span>Avg score</span></div>
                    <div><strong>${avgPresence}%</strong><span>Avg presence</span></div>
                    <div><strong>${this.currentSession.totalFillers}</strong><span>Filler words</span></div>
                </div>
                <p class="summary-source">${isLLM
                    ? 'Scores were generated by the Groq LLM.'
                    : '⚠️ Scores came from the offline heuristic (answer length &amp; fillers) — not AI.'}</p>
            `,
            actions: [{ label: 'Done', className: 'primary' }]
        });
    }

    showLoading(message = 'Working…') {
        const overlay = document.getElementById('loadingOverlay');
        overlay.querySelector('p').textContent = message;
        overlay.classList.remove('hidden');
    }

    hideLoading() {
        document.getElementById('loadingOverlay').classList.add('hidden');
    }
}

// Initialize app when DOM is loaded
let app;
document.addEventListener('DOMContentLoaded', () => {
    const speechSupport = SpeechManager.isSupported();
    if (!speechSupport.full) {
        console.warn('Speech features may not be fully supported in this browser');
    }
    app = new InterviewApp();
    window.app = app;
});
